import html
import importlib
import io
import json
import logging
import os
import re
import zipfile
import zlib
import base64
import time
from xml.etree import ElementTree

from app.services.ai_generator import _get_ai_client
from app.utils.role_normalizer import normalize_role


log = logging.getLogger(__name__)

ALLOWED_EXTENSIONS = {"pdf", "doc", "docx", "txt"}

_SECTION_KEYWORDS = {
    "resume", "curriculum", "vitae", "profile", "summary", "experience",
    "education", "skills", "projects", "objective", "contact", "mobile",
    "phone", "email", "linkedin", "github", "portfolio", "address",
    "about",
}

_NAME_SECTION_PHRASES = (
    "about me",
    "profile",
    "summary",
    "objective",
    "contact",
    "experience",
    "skills",
    "projects",
    "education",
)

_GENERIC_EMAIL_PREFIXES = {
    "hr", "jobs", "careers", "career", "recruitment", "hiring", "contact",
    "info", "support", "admin", "team",
}

_NOISE_LINE_PATTERNS = (
    "reportlab",
    "pdf library",
    "www.reportlab.com",
    "evaluation warning",
    "created with an evaluation copy",
    "generated by",
    "adobe acrobat",
)

_MIN_TEXT_QUALITY_FOR_DETERMINISTIC = 0.14
_AI_TEMP_UNAVAILABLE_UNTIL = 0.0


def allowed_file_extension(filename: str) -> bool:
    ext = get_file_extension(filename)
    return bool(ext and ext in ALLOWED_EXTENSIONS)


def get_file_extension(filename: str) -> str:
    if "." not in str(filename or ""):
        return ""
    return str(filename).rsplit(".", 1)[1].lower().strip()


def get_mime_type_for_filename(filename: str) -> str:
    ext = get_file_extension(filename)
    return {
        "pdf": "application/pdf",
        "docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "doc": "application/msword",
        "txt": "text/plain",
    }.get(ext, "application/octet-stream")


def _normalize_label(value: str) -> str:
    text = html.unescape(str(value or ""))
    text = text.replace("\u00e2\u20ac\u201c", "-").replace("\u00e2\u20ac\u201d", "-")
    text = text.replace("\u2013", "-").replace("\u2014", "-")
    text = re.sub(r"\s*-\s*", "-", text)
    text = re.sub(r"\s*\+\s*", "+", text)
    return " ".join(text.split()).strip().lower()

def _safe_json_from_text(raw: str):
    if not raw:
        return None
    cleaned = str(raw).strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?", "", cleaned, flags=re.IGNORECASE).strip()
        cleaned = re.sub(r"```$", "", cleaned).strip()
    if cleaned.startswith("{") and cleaned.endswith("}"):
        try:
            return json.loads(cleaned)
        except Exception:
            pass
    match = re.search(r"\{[\s\S]*\}", cleaned)
    if not match:
        return None
    try:
        return json.loads(match.group(0))
    except Exception:
        return None


def _is_ai_connectivity_error(exc: Exception):
    message = str(exc or "").lower()
    markers = (
        "timed out",
        "timeout",
        "connection refused",
        "connection reset",
        "temporarily unavailable",
        "name resolution",
        "dns",
        "503",
        "502",
        "504",
        "winerror 10061",
    )
    return any(marker in message for marker in markers)


def _sanitize_exception_message(exc: Exception):
    message = str(exc or "")
    message = re.sub(r"(key=)[^&\s]+", r"\1REDACTED", message, flags=re.IGNORECASE)
    api_key = os.getenv("GEMINI_API_KEY", "")
    if api_key:
        message = message.replace(api_key, "REDACTED")
    return message


def _ai_temporarily_unavailable():
    return time.time() < _AI_TEMP_UNAVAILABLE_UNTIL


def _mark_ai_temporarily_unavailable(seconds: int = 120):
    global _AI_TEMP_UNAVAILABLE_UNTIL
    _AI_TEMP_UNAVAILABLE_UNTIL = max(_AI_TEMP_UNAVAILABLE_UNTIL, time.time() + max(10, int(seconds)))


def _decode_bytes_best_effort(file_bytes: bytes):
    warnings = []
    for enc in ("utf-8", "utf-16", "latin-1"):
        try:
            text = file_bytes.decode(enc)
            if text:
                return text, enc, warnings
        except Exception:
            continue
    warnings.append("Unable to decode file bytes with supported text encodings.")
    return "", "unknown", warnings


_PDF_LITERAL_RE = re.compile(r"\((?:\\.|[^()]){1,4000}\)", re.DOTALL)
_PDF_HEX_RE = re.compile(r"<[0-9A-Fa-f\s]{2,8000}>", re.DOTALL)


def _iter_pdf_literal_tokens(blob_text: str, max_len: int = 6000):
    text = str(blob_text or "")
    tokens = []
    i = 0
    n = len(text)
    while i < n:
        if text[i] != "(":
            i += 1
            continue
        start = i
        i += 1
        depth = 1
        while i < n and depth > 0 and (i - start) <= max_len:
            ch = text[i]
            if ch == "\\":
                i += 2
                continue
            if ch == "(":
                depth += 1
            elif ch == ")":
                depth -= 1
            i += 1
        if depth == 0:
            tokens.append(text[start:i])
        else:
            i = start + 1
    return tokens


def _looks_like_text_fragment(value: str):
    text = str(value or "").strip()
    if len(text) < 2:
        return False
    printable_ratio = sum(1 for ch in text if ch.isprintable() and ch != "\x00") / max(len(text), 1)
    if printable_ratio < 0.8:
        return False
    alpha = sum(1 for ch in text if ch.isalpha())
    digit = sum(1 for ch in text if ch.isdigit())
    signal = alpha + digit + text.count("@") + text.count(".") + text.count("+") + text.count("/") + text.count("#")
    return signal / max(len(text), 1) >= 0.25


def _decode_pdf_literal_token(token: str):
    value = str(token or "")
    if len(value) < 2 or not value.startswith("(") or not value.endswith(")"):
        return ""
    source = value[1:-1]
    out = []
    i = 0
    while i < len(source):
        ch = source[i]
        if ch != "\\":
            out.append(ch)
            i += 1
            continue

        i += 1
        if i >= len(source):
            break

        esc = source[i]
        if esc in "nrtbf":
            out.append({"n": "\n", "r": "\r", "t": "\t", "b": "\b", "f": "\f"}[esc])
            i += 1
            continue
        if esc in "()\\":
            out.append(esc)
            i += 1
            continue
        if esc in "\n\r":
            if esc == "\r" and (i + 1) < len(source) and source[i + 1] == "\n":
                i += 2
            else:
                i += 1
            continue
        if esc.isdigit() and esc < "8":
            oct_digits = esc
            i += 1
            count = 1
            while i < len(source) and count < 3 and source[i].isdigit() and source[i] < "8":
                oct_digits += source[i]
                i += 1
                count += 1
            try:
                out.append(chr(int(oct_digits, 8)))
            except Exception:
                pass
            continue

        out.append(esc)
        i += 1

    return "".join(out)


def _decode_pdf_hex_token(token: str):
    value = str(token or "")
    if len(value) < 2 or not value.startswith("<") or not value.endswith(">"):
        return ""
    raw_hex = re.sub(r"[^0-9A-Fa-f]", "", value[1:-1])
    if not raw_hex:
        return ""
    if len(raw_hex) % 2 == 1:
        raw_hex += "0"
    try:
        data = bytes.fromhex(raw_hex)
    except Exception:
        return ""

    if not data:
        return ""
    if data.startswith(b"\xfe\xff"):
        return data[2:].decode("utf-16-be", errors="ignore")
    if data.startswith(b"\xff\xfe"):
        return data[2:].decode("utf-16-le", errors="ignore")
    if data.count(0) > (len(data) // 4):
        decoded = data.decode("utf-16-be", errors="ignore")
        if decoded:
            return decoded
    for enc in ("utf-8", "latin-1"):
        try:
            decoded = data.decode(enc, errors="ignore")
            if decoded:
                return decoded
        except Exception:
            continue
    return ""


def _is_noise_line(line: str):
    value = str(line or "").strip().lower()
    if not value:
        return True
    if any(pattern in value for pattern in _NOISE_LINE_PATTERNS):
        return True
    if re.search(r"(?:https?://|www\.)\S+", value):
        # Generic URL-only/footer noise; keep only if line appears to contain email.
        if "@" not in value:
            return True
    return False


def _repair_fragmented_pdf_text(text: str):
    if not text:
        return ""

    lines = str(text).splitlines()
    merged = []
    i = 0
    while i < len(lines):
        current = str(lines[i]).strip()
        if not current:
            merged.append("")
            i += 1
            continue

        if len(current) == 1 and re.match(r"[A-Za-z0-9@._+\-/]", current):
            parts = [current]
            j = i + 1
            while j < len(lines):
                nxt = str(lines[j]).strip()
                if not nxt:
                    break
                if len(nxt) == 1 and re.match(r"[A-Za-z0-9@._+\-/]", nxt):
                    parts.append(nxt)
                    j += 1
                    continue
                break
            if len(parts) >= 3:
                merged.append("".join(parts))
                i = j
                continue
        merged.append(current)
        i += 1

    repaired = []
    for raw_line in merged:
        line = re.sub(r"\s+", " ", raw_line).strip()
        if not line:
            continue

        line = re.sub(r"(?<=[a-z])(?=[A-Z])", " ", line)

        if _is_noise_line(line):
            continue

        # Join common tokenized punctuation around words/emails.
        line = re.sub(r"(?<=\w)\s*@\s*(?=\w)", "@", line)
        line = re.sub(r"(?<=\w)\s*\.\s*(?=\w)", ".", line)
        line = re.sub(r"(?<=\w)\s*-\s*(?=\w)", "-", line)
        line = re.sub(r"(?<=\w)\s*/\s*(?=\w)", "/", line)
        line = re.sub(r"(?<=\w)\s*\+\s*(?=\w)", "+", line)

        # Collapse spaced single-letter words: "J o h n D o e" -> "JohnDoe".
        line = re.sub(
            r"\b(?:[A-Za-z]\s+){2,}[A-Za-z]\b",
            lambda match: match.group(0).replace(" ", ""),
            line,
        )

        tokens = line.split()
        if len(tokens) >= 8:
            single_char_ratio = sum(1 for tok in tokens if len(tok) == 1) / len(tokens)
            if single_char_ratio >= 0.72:
                compact = "".join(tokens)
                if _looks_like_text_fragment(compact):
                    line = compact

        repaired.append(line)

    return "\n".join(repaired).strip()


def _extract_pdf_strings_from_blob(blob_text: str):
    chunks = []
    for token in _iter_pdf_literal_tokens(blob_text):
        content = _decode_pdf_literal_token(token)
        content = re.sub(r"\s+", " ", content).strip()
        if _looks_like_text_fragment(content):
            chunks.append(content)
    for token in _PDF_HEX_RE.findall(blob_text):
        content = _decode_pdf_hex_token(token)
        content = re.sub(r"\s+", " ", content).strip()
        if _looks_like_text_fragment(content):
            chunks.append(content)
    return chunks


def _extract_pdf_text_operators(blob_text: str):
    fragments = []
    for bt_block in re.findall(r"BT(.*?)ET", blob_text, flags=re.DOTALL):
        for snippet in re.findall(r"\((?:\\.|[^()]){1,4000}\)\s*Tj", bt_block, flags=re.DOTALL):
            token_match = _PDF_LITERAL_RE.search(snippet)
            if not token_match:
                continue
            decoded = _decode_pdf_literal_token(token_match.group(0))
            if decoded:
                fragments.append(decoded)

        for snippet in re.findall(r"<[0-9A-Fa-f\s]{2,8000}>\s*Tj", bt_block, flags=re.DOTALL):
            token_match = _PDF_HEX_RE.search(snippet)
            if not token_match:
                continue
            decoded = _decode_pdf_hex_token(token_match.group(0))
            if decoded:
                fragments.append(decoded)

        for array_body in re.findall(r"\[(.*?)\]\s*TJ", bt_block, flags=re.DOTALL):
            parts = []
            for token in re.findall(r"\((?:\\.|[^()]){1,4000}\)|<[0-9A-Fa-f\s]{2,8000}>", array_body, flags=re.DOTALL):
                if token.startswith("("):
                    decoded = _decode_pdf_literal_token(token)
                else:
                    decoded = _decode_pdf_hex_token(token)
                if decoded:
                    parts.append(decoded)
            if parts:
                fragments.append("".join(parts))

    cleaned = []
    for item in fragments:
        normalized = re.sub(r"\s+", " ", item).strip()
        if _looks_like_text_fragment(normalized):
            cleaned.append(normalized)
    return cleaned


def _text_quality_score(text: str):
    value = str(text or "")
    if not value:
        return 0.0

    total = len(value)
    if total < 20:
        return 0.0

    printable_ratio = sum(1 for ch in value if ch.isprintable() or ch in "\r\n\t") / max(total, 1)
    control_ratio = sum(1 for ch in value if ord(ch) < 32 and ch not in "\r\n\t") / max(total, 1)
    alpha_ratio = sum(1 for ch in value if ch.isalpha()) / max(total, 1)
    symbol_ratio = sum(1 for ch in value if (not ch.isalnum()) and (not ch.isspace())) / max(total, 1)

    words = re.findall(r"[A-Za-z]{3,}", value)
    word_like = [w for w in words if re.search(r"[aeiou]", w.lower())]
    word_density = len(word_like) / max(total / 12.0, 1.0)
    vowel_ratio = len(word_like) / max(len(words), 1)

    lower = value.lower()
    signal_terms = [
        "experience", "education", "skills", "profile", "summary", "developer",
        "engineer", "python", "java", "javascript", "project", "email", "phone",
        "responsibilities", "requirements", "job", "qualification",
    ]
    signal_hits = sum(1 for term in signal_terms if term in lower)

    common_terms = [
        "and", "with", "for", "the", "from", "years", "work", "role", "team",
        "design", "development", "testing", "candidate", "knowledge",
        "experience", "responsible", "skills", "education", "contact", "email",
        "resume", "objective", "software", "application", "project",
    ]
    common_hits = sum(1 for term in common_terms if re.search(rf"\b{re.escape(term)}\b", lower))

    score = 0.0
    score += max(0.0, min(1.0, printable_ratio)) * 0.10
    score += max(0.0, min(1.0, alpha_ratio / 0.35)) * 0.15
    score += max(0.0, min(1.0, word_density)) * 0.22
    score += max(0.0, min(1.0, vowel_ratio / 0.65)) * 0.18
    score += max(0.0, min(1.0, signal_hits / 6.0)) * 0.20
    score += max(0.0, min(1.0, common_hits / 8.0)) * 0.15
    score *= max(0.0, 1.0 - min(0.95, control_ratio * 8.0))
    score *= max(0.0, 1.0 - min(0.85, symbol_ratio * 1.6))

    if signal_hits <= 1 and common_hits <= 2:
        score = min(score, 0.12)

    return round(max(0.0, min(1.0, score)), 4)


def _pdf_binary_profile(file_bytes: bytes):
    payload = bytes(file_bytes or b"")
    image_count = len(re.findall(rb"/Subtype\s*/Image", payload))
    font_count = len(re.findall(rb"/Font\b", payload))
    tounicode_count = len(re.findall(rb"/ToUnicode\b", payload))
    flate_count = len(re.findall(rb"/FlateDecode\b", payload))
    dct_count = len(re.findall(rb"/DCTDecode\b", payload))
    ascii85_count = len(re.findall(rb"/ASCII85Decode\b", payload))
    return {
        "image_count": image_count,
        "font_count": font_count,
        "tounicode_count": tounicode_count,
        "flate_count": flate_count,
        "dct_count": dct_count,
        "ascii85_count": ascii85_count,
    }


def _extract_pdf_text_pdfplumber(file_bytes: bytes):
    warnings = []
    try:
        pdfplumber = importlib.import_module("pdfplumber")
    except Exception:
        warnings.append("pdfplumber dependency is not available on server.")
        return "", "pdfplumber_unavailable", warnings

    chunks = []
    try:
        with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
            for page in pdf.pages:
                chunks.append(page.extract_text() or "")
    except Exception as exc:
        warnings.append(f"Failed to parse PDF content via pdfplumber: {exc}")
        return "", "pdfplumber_failed", warnings

    return _repair_fragmented_pdf_text("\n".join(chunks).strip()), "pdfplumber", warnings


def _extract_pdf_text_pdfminer(file_bytes: bytes):
    warnings = []
    try:
        high_level = importlib.import_module("pdfminer.high_level")
        layout = importlib.import_module("pdfminer.layout")
    except Exception:
        warnings.append("pdfminer.six dependency is not available on server.")
        return "", "pdfminer_unavailable", warnings

    try:
        laparams = layout.LAParams(
            line_margin=0.3,
            char_margin=2.0,
            word_margin=0.2,
            boxes_flow=None,
        )
        text = high_level.extract_text(io.BytesIO(file_bytes), laparams=laparams) or ""
    except Exception as exc:
        warnings.append(f"Failed to parse PDF content via pdfminer: {exc}")
        return "", "pdfminer_failed", warnings

    return _repair_fragmented_pdf_text(text.strip()), "pdfminer", warnings


def _extract_pdf_text(file_bytes: bytes):
    def _extract_pdf_text_basic(raw_pdf_bytes: bytes):
        def _decode_stream_variants(stream_data: bytes):
            variants = []

            def _push(blob):
                if isinstance(blob, (bytes, bytearray)) and blob:
                    variants.append(bytes(blob))

            raw = (stream_data or b"").strip(b"\r\n")
            _push(raw)

            # Common PDF stream chain: ASCII85Decode -> FlateDecode.
            for candidate in list(variants):
                for adobe in (True, False):
                    try:
                        decoded = base64.a85decode(
                            candidate,
                            adobe=adobe,
                            ignorechars=b" \t\r\n\x0b\x0c",
                        )
                        _push(decoded)
                    except Exception:
                        continue

            # Flate decode on raw and ASCII85-decoded variants.
            for candidate in list(variants):
                for wbits in (zlib.MAX_WBITS, -zlib.MAX_WBITS, zlib.MAX_WBITS | 32):
                    try:
                        inflated = zlib.decompress(candidate, wbits)
                        _push(inflated)
                    except Exception:
                        continue

            # Deduplicate while preserving order.
            out = []
            seen = set()
            for blob in variants:
                if blob in seen:
                    continue
                seen.add(blob)
                out.append(blob)
            return out

        candidates = []

        # Pass 1: parse plain-text strings from entire file.
        root_blob = raw_pdf_bytes.decode("latin-1", errors="ignore")
        candidates.extend(_extract_pdf_text_operators(root_blob))
        candidates.extend(_extract_pdf_strings_from_blob(root_blob))

        # Pass 2: parse strings from stream objects, including Flate decompression.
        for match in re.finditer(rb"stream\r?\n(.*?)\r?\nendstream", raw_pdf_bytes, re.DOTALL):
            stream_data = match.group(1)
            blobs = _decode_stream_variants(stream_data)
            for blob in blobs:
                try:
                    decoded = blob.decode("latin-1", errors="ignore")
                except Exception:
                    continue
                candidates.extend(_extract_pdf_text_operators(decoded))
                candidates.extend(_extract_pdf_strings_from_blob(decoded))

        unique = []
        seen = set()
        for item in candidates:
            key = item.lower()
            if key in seen:
                continue
            seen.add(key)
            unique.append(item)

        raw_text = "\n".join(unique).strip()
        return _repair_fragmented_pdf_text(raw_text)

    profile = _pdf_binary_profile(file_bytes)

    attempts = []

    text_pdfplumber, method_pdfplumber, warn_pdfplumber = _extract_pdf_text_pdfplumber(file_bytes)
    attempts.append((text_pdfplumber, method_pdfplumber, warn_pdfplumber))

    text_pdfminer, method_pdfminer, warn_pdfminer = _extract_pdf_text_pdfminer(file_bytes)
    attempts.append((text_pdfminer, method_pdfminer, warn_pdfminer))

    text_basic = _extract_pdf_text_basic(file_bytes)
    attempts.append((text_basic, "pdf_basic", ["Used dependency-free PDF parser fallback."] if text_basic else []))

    best_text = ""
    best_method = "pdf_unknown"
    best_score = 0.0
    best_warnings = []

    for text, method, warn in attempts:
        score = _text_quality_score(text)
        if score > best_score:
            best_score = score
            best_text = text
            best_method = method
            best_warnings = list(warn or [])

    warnings = list(best_warnings)

    if best_text and best_score >= 0.14:
        log.info(
            "PDF extraction selected method=%s quality=%.3f profile=%s",
            best_method,
            best_score,
            profile,
        )
        return best_text, best_method, warnings

    if profile["image_count"] > 0 and profile["font_count"] == 0:
        warnings.append("PDF appears image-only; non-OCR extraction may not recover text.")
    elif profile["image_count"] > max(2, profile["font_count"] * 2):
        warnings.append("PDF appears image-heavy; extracted text quality is low.")
    elif profile["tounicode_count"] == 0:
        warnings.append("PDF font mapping is limited (no ToUnicode); extraction quality may be poor.")

    if best_text:
        warnings.append("Extracted PDF text is low quality and may be unusable.")
        return best_text, best_method, warnings

    warnings.append("No extractable text found in PDF.")
    return "", "pdf_unreadable", warnings


def _extract_docx_text(file_bytes: bytes):
    warnings = []
    parts = []
    xml_targets = {"word/document.xml"}
    try:
        with zipfile.ZipFile(io.BytesIO(file_bytes)) as archive:
            for name in archive.namelist():
                lower = name.lower()
                if lower in xml_targets or lower.startswith("word/header") or lower.startswith("word/footer"):
                    try:
                        parts.append(archive.read(name))
                    except Exception:
                        continue
    except Exception as exc:
        warnings.append(f"Unable to open DOCX archive: {exc}")
        return "", "docx_parse_failed", warnings

    if not parts:
        warnings.append("No extractable XML parts found in DOCX.")
        return "", "docx_empty", warnings

    text_segments = []
    ns = {"w": "http://schemas.openxmlformats.org/wordprocessingml/2006/main"}
    for part in parts:
        try:
            root = ElementTree.fromstring(part)
            # Join runs inside each paragraph so fragmented tokens
            # (common in DOCX) are reconstructed into readable lines.
            for paragraph in root.findall(".//w:p", ns):
                run_text = []
                for node in paragraph.findall(".//w:t", ns):
                    if node.text:
                        run_text.append(node.text)
                line = "".join(run_text)
                line = re.sub(r"\s+", " ", line).strip()
                if line:
                    text_segments.append(line)
        except Exception:
            continue

    # Fallback: if paragraph-based extraction yields nothing, use all text nodes.
    if not text_segments:
        for part in parts:
            try:
                root = ElementTree.fromstring(part)
                for node in root.findall(".//w:t", ns):
                    if node.text:
                        token = re.sub(r"\s+", " ", node.text).strip()
                        if token:
                            text_segments.append(token)
            except Exception:
                continue

    text = "\n".join(text_segments).strip()
    if not text:
        warnings.append("DOCX text nodes were present but empty.")
    return text, "docx_xml", warnings


def _extract_doc_text(file_bytes: bytes):
    text, encoding, warnings = _decode_bytes_best_effort(file_bytes)
    warnings.append("Legacy .doc parsing is best effort and may be incomplete.")
    # Heuristic: if too many replacement chars, treat as weak extraction.
    replacement_ratio = (text.count("\ufffd") / max(len(text), 1)) if text else 1.0
    if replacement_ratio > 0.1:
        warnings.append("Legacy .doc content appears partially unreadable.")
    return text, f"doc_best_effort_{encoding}", warnings


def extract_text_from_file(filename: str, file_bytes: bytes):
    ext = get_file_extension(filename)
    if ext not in ALLOWED_EXTENSIONS:
        return {
            "text": "",
            "file_type": ext or "unknown",
            "extraction_method": "unsupported",
            "text_length": 0,
            "text_quality": 0.0,
            "warnings": [f"Unsupported file type: .{ext}" if ext else "Missing file extension."],
            "error": "Unsupported file type",
        }

    warnings = []
    text = ""
    method = "unknown"

    if ext == "pdf":
        text, method, warnings = _extract_pdf_text(file_bytes)
    elif ext == "docx":
        text, method, warnings = _extract_docx_text(file_bytes)
    elif ext == "txt":
        text, encoding, decode_warnings = _decode_bytes_best_effort(file_bytes)
        method = f"txt_decode_{encoding}"
        warnings.extend(decode_warnings)
    else:
        text, method, warnings = _extract_doc_text(file_bytes)

    return {
        "text": text or "",
        "file_type": ext,
        "extraction_method": method,
        "text_length": len(text or ""),
        "text_quality": _text_quality_score(text or ""),
        "warnings": warnings,
        "error": None,
    }


def _normalize_obfuscated_email_text(text: str) -> str:
    if not text:
        return ""
    out = str(text)
    out = re.sub(r"(?i)\[\s*at\s*\]|\(\s*at\s*\)|\{\s*at\s*\}", "@", out)
    out = re.sub(r"(?i)\[\s*dot\s*\]|\(\s*dot\s*\)|\{\s*dot\s*\}", ".", out)
    out = re.sub(r"(?i)(?<=\w)\s+at\s+(?=\w)", "@", out)
    out = re.sub(r"(?i)(?<=\w)\s+dot\s+(?=\w)", ".", out)
    out = re.sub(r"(?<=\w)\s*@\s*(?=\w)", "@", out)
    out = re.sub(r"(?<=\w)\s*\.\s*(?=\w)", ".", out)
    out = re.sub(r"(?<=\w)\s*-\s*(?=\w)", "-", out)
    return out


def _extract_emails(text: str):
    normalized = _normalize_obfuscated_email_text(text)
    pattern = r"[a-zA-Z0-9._%+\-]{1,64}@[a-zA-Z0-9.\-]{1,253}\.[a-zA-Z]{2,24}"
    raw = re.findall(pattern, normalized)

    if not raw:
        # Fallback for heavily fragmented PDF text where email chars are spaced.
        relaxed_pattern = r"[a-zA-Z0-9._%+\-\s]{1,80}\s*@\s*[a-zA-Z0-9.\-\s]{1,120}\s*\.\s*[a-zA-Z]{2,12}"
        relaxed_hits = re.findall(relaxed_pattern, normalized)
        for item in relaxed_hits:
            compact = re.sub(r"\s+", "", item or "")
            if re.fullmatch(pattern, compact or ""):
                raw.append(compact)

    unique = []
    seen = set()
    for value in raw:
        item = value.strip().strip(".,;:!?)(")
        lower = item.lower()
        local, _, domain = lower.partition("@")
        if not local or not domain:
            continue
        if len(local) > 64 or len(domain) > 253:
            continue
        if ".." in local or ".." in domain:
            continue
        if local.startswith(".") or local.endswith("."):
            continue
        if domain.startswith(".") or domain.endswith("."):
            continue
        if lower in seen:
            continue
        seen.add(lower)
        unique.append(item)
    return unique


def _score_email(email: str):
    email = str(email or "").strip()
    if "@" not in email:
        return -999
    local, domain = email.split("@", 1)
    local_lower = local.lower()
    score = 0
    if local_lower not in _GENERIC_EMAIL_PREFIXES:
        score += 3
    if any(ch.isdigit() for ch in local):
        score -= 1
    if "." in local or "_" in local:
        score += 1
    if domain.lower().endswith((".edu", ".ac.in", ".org")):
        score += 1
    if len(local) < 3:
        score -= 1
    return score


def _line_is_name_candidate(line: str):
    line = str(line or "").strip()
    if not line:
        return False
    lower = line.lower()
    if "@" in line or "http://" in lower or "https://" in lower:
        return False
    if _is_noise_line(line):
        return False
    if any(ext in lower for ext in (".com", ".net", ".org", ".io", ".in")):
        return False
    if re.search(r"\babout\s+me\b", lower):
        return False
    if any(keyword in lower for keyword in _SECTION_KEYWORDS):
        return False
    if len(line) > 64:
        return False
    if sum(ch.isdigit() for ch in line) > 1:
        return False

    tokens = re.findall(r"[A-Za-z][A-Za-z.'\-]*", line)
    if len(tokens) < 2 or len(tokens) > 5:
        return False
    alpha_chars = sum(ch.isalpha() for ch in line)
    if alpha_chars < 4:
        return False
    return True


def _score_name_line(line: str, position: int):
    tokens = re.findall(r"[A-Za-z][A-Za-z.'\-]*", line)
    score = 0
    if position < 2:
        score += 35
    elif position < 5:
        score += 25
    elif position < 10:
        score += 12
    else:
        score += 6

    if len(tokens) in (2, 3):
        score += 32
    elif len(tokens) == 4:
        score += 18
    else:
        score += 8

    if all((t[:1].isupper() or t.isupper()) for t in tokens):
        score += 18

    if any(len(t) == 1 for t in tokens):
        score -= 12

    if sum(ch.isdigit() for ch in line) > 0:
        score -= 20

    return max(0, min(score, 100))


def _extract_name_candidate(text: str):
    def _trim_name_suffix_sections(value: str):
        line = re.sub(r"\s+", " ", str(value or "")).strip(" ,|-")
        if not line:
            return ""
        lower = line.lower()
        for phrase in _NAME_SECTION_PHRASES:
            marker = f" {phrase}"
            pos = lower.find(marker)
            if pos > 0:
                line = line[:pos].strip(" ,|-")
                lower = line.lower()
        line = re.sub(
            r"\s+(?:about|profile|summary|objective|contact|experience|skills|projects|education)\s*$",
            "",
            line,
            flags=re.IGNORECASE,
        ).strip(" ,|-")
        return line

    lines = []
    raw_lines = []
    for ln in str(text or "").splitlines():
        raw = re.sub(r"\s+", " ", ln).strip(" ,|-")
        if not raw:
            continue
        trimmed = _trim_name_suffix_sections(raw)
        if not trimmed:
            continue
        lines.append(trimmed)
        raw_lines.append(raw)

    def _is_single_name_word(value: str):
        token = str(value or "").strip()
        if not re.fullmatch(r"[A-Za-z][A-Za-z.'\-]{1,24}", token):
            return False
        lower = token.lower()
        if lower in _SECTION_KEYWORDS:
            return False
        if _is_noise_line(token):
            return False
        return True

    candidates = [(line, idx) for idx, line in enumerate(lines[:40])]
    for idx in range(min(len(lines) - 1, 20)):
        first = lines[idx]
        second = lines[idx + 1]
        if _is_single_name_word(first) and _is_single_name_word(second):
            candidates.append((f"{first} {second}", idx))
            continue

        # If a heading was attached to the first line (e.g. "MOHIT ABOUT ME"),
        # pair the cleaned first-name token with an uppercase surname token from next line.
        raw_first = raw_lines[idx] if idx < len(raw_lines) else ""
        raw_first_lower = raw_first.lower()
        if _is_single_name_word(first) and any(phrase in raw_first_lower for phrase in _NAME_SECTION_PHRASES):
            m = re.match(r"([A-Za-z][A-Za-z.'\-]{1,24})\b", second)
            if m:
                surname = m.group(1)
                if surname.isupper() and surname.lower() not in _SECTION_KEYWORDS:
                    candidates.append((f"{first} {surname}", idx))

    best_name = None
    best_score = 0
    for line, idx in candidates:
        if not _line_is_name_candidate(line):
            continue
        score = _score_name_line(line, idx)
        if score > best_score:
            best_name = line
            best_score = score
    confidence = round(best_score / 100.0, 3)
    if best_name and best_score >= 60:
        return best_name, confidence
    return None, confidence


def _ai_resume_extraction(text: str):
    if _ai_temporarily_unavailable():
        return None

    client = _get_ai_client()
    if not client:
        return None

    prompt = f"""
Extract candidate name and candidate email from this resume text.
Return strict JSON only, no markdown:
{{
  "name": "string or null",
  "email": "string or null",
  "confidence_name": 0.0,
  "confidence_email": 0.0
}}

Resume text:
{text[:12000]}
"""
    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            config={
                "response_mime_type": "application/json",
                "temperature": 0.1,
            },
        )
        payload = _safe_json_from_text(getattr(response, "text", "") or "")
        if not isinstance(payload, dict):
            return None
        return {
            "name": str(payload.get("name")).strip() if payload.get("name") else None,
            "email": str(payload.get("email")).strip() if payload.get("email") else None,
            "confidence_name": float(payload.get("confidence_name") or 0.0),
            "confidence_email": float(payload.get("confidence_email") or 0.0),
        }
    except Exception as exc:
        if _is_ai_connectivity_error(exc):
            _mark_ai_temporarily_unavailable()
        log.warning("AI resume extraction failed: %s", _sanitize_exception_message(exc))
        return None


def _build_genai_document_part(file_bytes: bytes, mime_type: str):
    try:
        types_mod = importlib.import_module("google.genai.types")
        part_cls = getattr(types_mod, "Part", None)
        if part_cls and hasattr(part_cls, "from_bytes"):
            return part_cls.from_bytes(data=file_bytes, mime_type=mime_type)
    except Exception:
        pass

    if not file_bytes:
        return None

    return {
        "inlineData": {
            "mimeType": mime_type or "application/octet-stream",
            "data": base64.b64encode(file_bytes).decode("ascii"),
        }
    }


def _ai_resume_extraction_from_document(file_bytes: bytes, mime_type: str):
    if _ai_temporarily_unavailable():
        return None

    client = _get_ai_client()
    if not client or not file_bytes:
        return None

    part = _build_genai_document_part(file_bytes, mime_type)
    if part is None:
        return None

    prompt = """
Extract candidate name and candidate email from this resume document.
Return strict JSON only, no markdown:
{
  "name": "string or null",
  "email": "string or null",
  "confidence_name": 0.0,
  "confidence_email": 0.0
}
"""
    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=[prompt, part],
            config={
                "response_mime_type": "application/json",
                "temperature": 0.1,
            },
        )
        payload = _safe_json_from_text(getattr(response, "text", "") or "")
        if not isinstance(payload, dict):
            return None
        return {
            "name": str(payload.get("name")).strip() if payload.get("name") else None,
            "email": str(payload.get("email")).strip() if payload.get("email") else None,
            "confidence_name": float(payload.get("confidence_name") or 0.0),
            "confidence_email": float(payload.get("confidence_email") or 0.0),
        }
    except Exception as exc:
        if _is_ai_connectivity_error(exc):
            _mark_ai_temporarily_unavailable()
        log.warning("AI resume extraction from document failed: %s", _sanitize_exception_message(exc))
        return None


def extract_resume_identity(
    text: str,
    filename: str,
    use_ai_fallback: bool = True,
    source_file_bytes: bytes = None,
    source_mime_type: str = None,
    text_quality: float = 1.0,
):
    warnings = []
    quality = float(text_quality or 0.0)
    can_use_deterministic = quality >= _MIN_TEXT_QUALITY_FOR_DETERMINISTIC

    emails = _extract_emails(text) if can_use_deterministic else []
    email = max(emails, key=_score_email) if emails else None
    email_conf = 0.92 if email else 0.0

    if can_use_deterministic:
        name, name_conf = _extract_name_candidate(text)
    else:
        name, name_conf = (None, 0.0)
        warnings.append("Resume text quality is low; deterministic extraction disabled.")

    used_ai = False
    if use_ai_fallback and can_use_deterministic and ((not name) or (not email) or name_conf < 0.7):
        ai_data = _ai_resume_extraction(text)
        if ai_data:
            used_ai = True
            ai_name = ai_data.get("name")
            ai_email = ai_data.get("email")
            ai_name_conf = max(0.0, min(1.0, ai_data.get("confidence_name", 0.0)))
            ai_email_conf = max(0.0, min(1.0, ai_data.get("confidence_email", 0.0)))
            if ai_name and (not name or ai_name_conf > (name_conf + 0.08)):
                name = ai_name
                name_conf = ai_name_conf
            if ai_email and (not email or ai_email_conf > (email_conf + 0.04)):
                email = ai_email
                email_conf = ai_email_conf
        else:
            warnings.append("AI resume text fallback returned no result.")

    if use_ai_fallback and source_file_bytes and ((not name) or (not email)):
        ai_doc_data = _ai_resume_extraction_from_document(
            source_file_bytes,
            source_mime_type or get_mime_type_for_filename(filename),
        )
        if ai_doc_data:
            used_ai = True
            ai_name = ai_doc_data.get("name")
            ai_email = ai_doc_data.get("email")
            ai_name_conf = max(0.0, min(1.0, ai_doc_data.get("confidence_name", 0.0)))
            ai_email_conf = max(0.0, min(1.0, ai_doc_data.get("confidence_email", 0.0)))
            if ai_name and (not name or ai_name_conf >= 0.62):
                name = ai_name
                name_conf = max(name_conf, ai_name_conf)
            if ai_email and (not email or ai_email_conf >= 0.62):
                email = ai_email
                email_conf = max(email_conf, ai_email_conf)
        else:
            warnings.append("AI resume document fallback returned no result.")
            warnings.append(
                "AI service unavailable or unreachable. Verify GEMINI_API_KEY and outbound access to Gemini API."
            )

    messages = {}
    if not name:
        messages["name"] = "Name not found in resume."
    if not email:
        messages["email"] = "Email not found in resume."

    overall_conf = round((name_conf + email_conf) / 2.0, 3)
    log.info(
        "Resume extraction completed | file=%s name_found=%s email_found=%s used_ai=%s confidence=%.3f",
        filename,
        bool(name),
        bool(email),
        used_ai,
        overall_conf,
    )

    return {
        "name": name,
        "email": email,
        "name_found": bool(name),
        "email_found": bool(email),
        "messages": messages,
        "confidence": {
            "name": round(name_conf, 3),
            "email": round(email_conf, 3),
            "overall": overall_conf,
        },
        "warnings": warnings,
        "used_ai": used_ai,
    }


_ROLE_PROFILES = {
    "python_entry": {
        "family": "python",
        "title_phrases": ["python developer", "junior python", "entry level python", "python intern"],
        "skills": ["python", "flask", "django", "api", "oop"],
        "seniority": ["entry level", "junior", "fresher", "0-2 years", "1 year", "2 years"],
        "years": (0, 2),
    },
    "java_entry": {
        "family": "java",
        "title_phrases": ["java developer", "junior java", "entry level java", "java intern"],
        "skills": ["java", "spring", "hibernate", "junit", "maven"],
        "seniority": ["entry level", "junior", "fresher", "0-2 years", "1 year", "2 years"],
        "years": (0, 2),
    },
    "js_entry": {
        "family": "javascript",
        "title_phrases": ["javascript developer", "frontend developer", "junior javascript", "node.js developer"],
        "skills": ["javascript", "node.js", "react", "html", "css"],
        "seniority": ["entry level", "junior", "fresher", "0-2 years"],
        "years": (0, 2),
    },
    "python_qa_linux": {
        "family": "python",
        "title_phrases": ["python qa", "python test engineer", "qa automation python", "linux qa"],
        "skills": ["python", "qa", "linux", "automation", "testing"],
        "seniority": ["4+ years", "4 years", "5 years"],
        "years": (4, 20),
    },
    "python_qa": {
        "family": "python",
        "title_phrases": ["python qa", "qa engineer python", "test automation python"],
        "skills": ["python", "qa", "automation", "testing", "selenium"],
        "seniority": ["4+ years", "4 years", "5 years"],
        "years": (4, 20),
    },
    "python_dev": {
        "family": "python",
        "title_phrases": ["python developer", "backend python developer", "software engineer python"],
        "skills": ["python", "django", "flask", "api", "backend"],
        "seniority": ["4+ years", "4 years", "5 years"],
        "years": (4, 20),
    },
    "python_ai_ml": {
        "family": "python",
        "title_phrases": ["machine learning engineer", "ai engineer", "python ai", "data scientist"],
        "skills": ["python", "machine learning", "ml", "ai", "pytorch", "tensorflow"],
        "seniority": ["4+ years", "5 years"],
        "years": (4, 20),
    },
    "java_aws": {
        "family": "java",
        "title_phrases": ["java aws developer", "java cloud developer", "aws java engineer"],
        "skills": ["java", "aws", "spring boot", "microservices", "cloud"],
        "seniority": ["5+ years", "5 years", "6 years"],
        "years": (5, 25),
    },
    "java_qa": {
        "family": "java",
        "title_phrases": ["java qa", "qa engineer java", "automation java"],
        "skills": ["java", "qa", "automation", "selenium", "testing"],
        "seniority": ["5+ years", "5 years", "6 years"],
        "years": (5, 25),
    },
    "bmc_engineer": {
        "family": "c_cpp",
        "title_phrases": ["bmc engineer", "firmware engineer", "bios engineer"],
        "skills": ["bmc", "firmware", "bios", "embedded", "c language"],
        "seniority": ["2-5 years", "3 years", "4 years", "5 years"],
        "years": (2, 5),
    },
    "linux_kernel_dd": {
        "family": "c_cpp",
        "title_phrases": ["linux kernel engineer", "device driver engineer", "kernel developer"],
        "skills": ["linux kernel", "device driver", "kernel", "c", "embedded"],
        "seniority": ["3-5 years", "3 years", "4 years", "5 years"],
        "years": (3, 5),
    },
    "systems_architect_cpp": {
        "family": "c_cpp",
        "title_phrases": ["systems architect", "c++ architect", "system design c++"],
        "skills": ["c++", "system design", "architecture", "distributed systems"],
        "seniority": ["3-5 years", "4 years", "5 years"],
        "years": (3, 5),
    },
}

_FAMILY_KEYWORDS = {
    "python": ["python", "django", "flask", "pandas"],
    "java": ["java", "spring", "j2ee", "hibernate"],
    "javascript": ["javascript", "node.js", "react", "angular", "typescript"],
    "c_cpp": ["c++", "cpp", "kernel", "device driver", "firmware", "embedded"],
}


def _compact_text(value: str):
    return re.sub(r"[^a-z0-9]+", "", str(value or "").lower())


def _count_hits(text_lower: str, keywords, compact_text: str = ""):
    score = 0
    compact_source = compact_text or _compact_text(text_lower)
    for kw in keywords:
        key = kw.lower().strip()
        if not key:
            continue
        if " " in key or "." in key or "+" in key:
            if key in text_lower:
                score += 1
                continue
            compact_key = _compact_text(key)
            if compact_key and compact_key in compact_source:
                score += 1
        else:
            if re.search(rf"\b{re.escape(key)}\b", text_lower):
                score += 1
                continue
            compact_key = _compact_text(key)
            if compact_key and compact_key in compact_source:
                score += 1
    return score


def _extract_years(text_lower: str):
    matches = re.findall(r"(\d{1,2})\s*(?:\+|plus)?\s*(?:years|yrs|year)", text_lower)
    years = [int(m) for m in matches if m.isdigit()]
    return max(years) if years else None


def _ai_jd_role_match(text: str, available_roles):
    if _ai_temporarily_unavailable():
        return None

    client = _get_ai_client()
    if not client:
        return None
    role_list = "\n".join(f"- {role}" for role in available_roles)
    prompt = f"""
Choose the single best matching role for the following JD.
You must choose from this list only or return null:
{role_list}

Return strict JSON only:
{{
  "role": "exact role label or null",
  "confidence": 0.0,
  "reason": "short reason"
}}

JD text:
{text[:14000]}
"""
    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt,
            config={
                "response_mime_type": "application/json",
                "temperature": 0.1,
            },
        )
        payload = _safe_json_from_text(getattr(response, "text", "") or "")
        if not isinstance(payload, dict):
            return None
        role = payload.get("role")
        if role is not None:
            role = str(role).strip()
        confidence = float(payload.get("confidence") or 0.0)
        reason = str(payload.get("reason") or "").strip()
        return {"role": role, "confidence": confidence, "reason": reason}
    except Exception as exc:
        if _is_ai_connectivity_error(exc):
            _mark_ai_temporarily_unavailable()
        log.warning("AI JD role match failed: %s", _sanitize_exception_message(exc))
        return None


def _ai_jd_role_match_from_document(file_bytes: bytes, mime_type: str, available_roles):
    if _ai_temporarily_unavailable():
        return None

    client = _get_ai_client()
    if not client or not file_bytes:
        return None

    part = _build_genai_document_part(file_bytes, mime_type)
    if part is None:
        return None

    role_list = "\n".join(f"- {role}" for role in available_roles)
    prompt = f"""
Choose the single best matching role for the following JD document.
You must choose from this list only or return null:
{role_list}

Return strict JSON only:
{{
  "role": "exact role label or null",
  "confidence": 0.0,
  "reason": "short reason"
}}
"""
    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=[prompt, part],
            config={
                "response_mime_type": "application/json",
                "temperature": 0.1,
            },
        )
        payload = _safe_json_from_text(getattr(response, "text", "") or "")
        if not isinstance(payload, dict):
            return None
        role = payload.get("role")
        if role is not None:
            role = str(role).strip()
        confidence = float(payload.get("confidence") or 0.0)
        reason = str(payload.get("reason") or "").strip()
        return {"role": role, "confidence": confidence, "reason": reason}
    except Exception as exc:
        if _is_ai_connectivity_error(exc):
            _mark_ai_temporarily_unavailable()
        log.warning("AI JD role match from document failed: %s", _sanitize_exception_message(exc))
        return None


def _infer_role_from_filename(source_filename: str, available_roles):
    raw = str(source_filename or "").strip()
    if not raw:
        return None, ""

    stem = raw.rsplit("/", 1)[-1].rsplit("\\", 1)[-1]
    if "." in stem:
        stem = stem.rsplit(".", 1)[0]

    normalized_stem = _normalize_label(stem)
    compact = _compact_text(normalized_stem)
    if not compact:
        return None, ""

    key_to_label = {}
    for label in available_roles:
        role_key = normalize_role(label)
        if role_key:
            key_to_label[role_key] = label

    def has(token: str):
        return _compact_text(token) in compact

    candidates = []
    if has("javascript") and (has("entry") or has("0-2")):
        candidates.append("js_entry")
    if has("python") and (has("entry") or has("0-2")):
        candidates.append("python_entry")
    if has("java") and (not has("javascript")) and (has("entry") or has("0-2")):
        candidates.append("java_entry")
    if has("java") and has("aws"):
        candidates.append("java_aws")
    if has("python") and has("qa") and has("linux"):
        candidates.append("python_qa_linux")
    if has("python") and has("qa"):
        candidates.append("python_qa")
    if has("python") and (has("development") or has("developer") or has("dev")):
        candidates.append("python_dev")
    if has("python") and (has("ai") or has("ml")):
        candidates.append("python_ai_ml")
    if has("java") and has("qa"):
        candidates.append("java_qa")
    if has("bmc"):
        candidates.append("bmc_engineer")
    if has("kernel") or has("driver"):
        candidates.append("linux_kernel_dd")
    if has("architect") or has("cpp") or has("c++"):
        candidates.append("systems_architect_cpp")

    for role_key in candidates:
        label = key_to_label.get(role_key)
        if label:
            return label, stem

    return None, stem


def _resolve_ai_role_label(ai_role_raw, normalized_available, key_to_label):
    raw = str(ai_role_raw or "").strip()
    if not raw:
        return None

    normalized_ai = _normalize_label(raw)
    if normalized_ai in normalized_available:
        return normalized_available[normalized_ai]

    direct_role_key = normalize_role(raw)
    if direct_role_key and direct_role_key in key_to_label:
        return key_to_label[direct_role_key]

    compact_ai = _compact_text(normalized_ai)
    if not compact_ai:
        return None

    best_label = None
    best_score = 0
    ai_tokens = set(re.findall(r"[a-z]+", normalized_ai))

    for role_key, label in key_to_label.items():
        normalized_label = _normalize_label(label)
        compact_label = _compact_text(normalized_label)
        compact_key = _compact_text(role_key.replace("_", " "))

        score = 0
        if compact_ai == compact_label or compact_ai == compact_key:
            score = 5
        elif compact_ai in compact_label or compact_ai in compact_key:
            score = 4
        elif compact_label in compact_ai or compact_key in compact_ai:
            score = 3
        else:
            label_tokens = set(re.findall(r"[a-z]+", normalized_label.split("(")[0]))
            overlap = len(ai_tokens & label_tokens)
            if overlap >= 2:
                score = 2

        if score > best_score:
            best_score = score
            best_label = label

    if best_score >= 3:
        return best_label
    return None


def match_role_from_jd(
    text: str,
    available_roles,
    use_ai_fallback: bool = True,
    source_file_bytes: bytes = None,
    source_mime_type: str = None,
    text_quality: float = 1.0,
    source_filename: str = None,
):
    warnings = []
    normalized_available = {}
    key_to_label = {}
    for label in available_roles:
        normalized_label = _normalize_label(label)
        role_key = normalize_role(label)
        if not role_key:
            continue
        normalized_available[normalized_label] = label
        key_to_label[role_key] = label

    if not key_to_label:
        return {
            "role": None,
            "role_found": False,
            "message": "No role fits perfectly among available roles.",
            "confidence": {"score": 0, "normalized": 0.0, "margin": 0.0},
            "top_matches": [],
            "warnings": ["No valid roles were provided for JD matching."],
            "used_ai": False,
        }

    quality = float(text_quality or 0.0)
    can_use_deterministic = quality >= _MIN_TEXT_QUALITY_FOR_DETERMINISTIC

    text_lower = str(text or "").lower()
    compact_source = _compact_text(text_lower)
    years = _extract_years(text_lower) if can_use_deterministic else None

    family_strength = {}
    for family, keywords in _FAMILY_KEYWORDS.items():
        family_strength[family] = _count_hits(text_lower, keywords, compact_source) if can_use_deterministic else 0
    dominant_family = max(family_strength, key=family_strength.get) if family_strength else None
    dominant_strength = family_strength.get(dominant_family, 0) if dominant_family else 0

    role_scores = []
    for role_key, label in key_to_label.items():
        profile = _ROLE_PROFILES.get(role_key, {})
        if can_use_deterministic:
            title_hits = _count_hits(text_lower, profile.get("title_phrases", []), compact_source)
            skill_hits = _count_hits(text_lower, profile.get("skills", []), compact_source)
            seniority_hits = _count_hits(text_lower, profile.get("seniority", []), compact_source)
            family = profile.get("family")
            family_hits = family_strength.get(family, 0)

            score = (title_hits * 4) + (skill_hits * 2) + (seniority_hits * 2) + min(family_hits, 3)

            expected_years = profile.get("years")
            if years is not None and expected_years:
                min_years, max_years = expected_years
                if years < min_years:
                    score -= 3
                if years > max_years + 1:
                    score -= 2

            if dominant_family and dominant_strength >= 3 and family != dominant_family:
                score -= 3
        else:
            title_hits = 0
            skill_hits = 0
            seniority_hits = 0
            score = 0

        role_scores.append(
            {
                "role": label,
                "role_key": role_key,
                "score": score,
                "title_hits": title_hits,
                "skill_hits": skill_hits,
                "seniority_hits": seniority_hits,
            }
        )

    role_scores.sort(key=lambda item: item["score"], reverse=True)
    top_matches = [{"role": item["role"], "score": item["score"]} for item in role_scores[:3]]
    top_score = role_scores[0]["score"] if role_scores else 0
    second_score = role_scores[1]["score"] if len(role_scores) > 1 else 0
    margin = top_score - second_score
    normalized_conf = max(0.0, min(1.0, (0.7 * (top_score / 12.0)) + (0.3 * (margin / 6.0))))

    role = None
    role_found = False
    message = "No role fits perfectly among available roles."
    used_ai = False

    if (can_use_deterministic and top_score >= 5 and margin >= 1 and normalized_conf >= 0.50):
        role = role_scores[0]["role"]
        role_found = True
        message = ""
    elif use_ai_fallback:
        if not can_use_deterministic:
            warnings.append("JD text quality is low; deterministic role match disabled.")
        ai_data = _ai_jd_role_match(text, [item["role"] for item in role_scores])
        if ai_data:
            used_ai = True
            ai_role_raw = ai_data.get("role")
            ai_conf = max(0.0, min(1.0, float(ai_data.get("confidence") or 0.0)))
            ai_reason = ai_data.get("reason") or ""
            resolved_ai_role = _resolve_ai_role_label(ai_role_raw, normalized_available, key_to_label)
            relaxed_ai_accept = (not can_use_deterministic and top_score <= 1 and ai_conf >= 0.45)
            missing_conf_accept = (not can_use_deterministic and ai_conf == 0.0)
            if (
                resolved_ai_role
                and (ai_conf >= 0.72 or relaxed_ai_accept or missing_conf_accept)
            ):
                role = resolved_ai_role
                role_found = True
                message = ""
                if ai_conf > 0.0:
                    normalized_conf = max(normalized_conf, ai_conf)
                else:
                    normalized_conf = max(normalized_conf, 0.62)
                    warnings.append("AI role confidence missing; accepted constrained role output.")
            elif ai_role_raw:
                warnings.append(f"AI returned unmatched/low-confidence role: {ai_role_raw}")
            elif ai_reason:
                warnings.append(ai_reason)
        else:
            warnings.append("AI JD text fallback returned no result.")

    if (not role_found) and use_ai_fallback and source_file_bytes:
        ai_doc_data = _ai_jd_role_match_from_document(
            source_file_bytes,
            source_mime_type or "application/pdf",
            [item["role"] for item in role_scores],
        )
        if ai_doc_data:
            used_ai = True
            ai_role_raw = ai_doc_data.get("role")
            ai_conf = max(0.0, min(1.0, float(ai_doc_data.get("confidence") or 0.0)))
            ai_reason = ai_doc_data.get("reason") or ""
            resolved_ai_role = _resolve_ai_role_label(ai_role_raw, normalized_available, key_to_label)
            relaxed_doc_accept = (not can_use_deterministic and top_score <= 1 and ai_conf >= 0.40)
            missing_conf_accept = (not can_use_deterministic and ai_conf == 0.0)
            if (
                resolved_ai_role
                and (ai_conf >= 0.68 or relaxed_doc_accept or missing_conf_accept)
            ):
                role = resolved_ai_role
                role_found = True
                message = ""
                if ai_conf > 0.0:
                    normalized_conf = max(normalized_conf, ai_conf)
                else:
                    normalized_conf = max(normalized_conf, 0.60)
                    warnings.append("AI document role confidence missing; accepted constrained role output.")
            elif ai_role_raw:
                warnings.append(f"AI document returned unmatched/low-confidence role: {ai_role_raw}")
            elif ai_reason:
                warnings.append(ai_reason)
        else:
            warnings.append("AI JD document fallback returned no result.")
            warnings.append(
                "AI service unavailable or unreachable. Verify GEMINI_API_KEY and outbound access to Gemini API."
            )

    if not role_found:
        inferred_role, filename_hint = _infer_role_from_filename(source_filename, [item["role"] for item in role_scores])
        if inferred_role:
            role = inferred_role
            role_found = True
            message = ""
            normalized_conf = max(normalized_conf, 0.55)
            if filename_hint:
                warnings.append(f"Role inferred from filename hint: {filename_hint}")

    if (not role_found) and can_use_deterministic and top_score >= 2:
        role = role_scores[0]["role"]
        role_found = True
        message = ""
        normalized_conf = max(normalized_conf, 0.42)
        warnings.append("Role selected via deterministic best-effort fallback.")

    log.info(
        "JD role matching completed | role_found=%s role=%s used_ai=%s score=%s margin=%s confidence=%.3f",
        role_found,
        role,
        used_ai,
        top_score,
        margin,
        normalized_conf,
    )

    return {
        "role": role,
        "role_found": role_found,
        "message": message,
        "confidence": {
            "score": top_score,
            "normalized": round(normalized_conf, 3),
            "margin": round(float(margin), 3),
        },
        "top_matches": top_matches,
        "warnings": warnings,
        "used_ai": used_ai,
    }
