"""Add test_session_id to reports

Revision ID: ce48db70d5b5
Revises: f8788da4b21f
Create Date: 2026-02-24 12:57:25.427388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce48db70d5b5'
down_revision = 'f8788da4b21f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_session_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_reports_test_session_id', 'test_sessions', ['test_session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reports_test_session_id', type_='foreignkey')
        batch_op.drop_column('test_session_id')

    # ### end Alembic commands ###
