"""Initial models: Candidate, TestSession, RoundResult, Report

Revision ID: f8788da4b21f
Revises: 
Create Date: 2026-02-13 12:09:31.019252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8788da4b21f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidates_email'), ['email'], unique=True)

    op.create_table('test_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('role_key', sa.String(length=50), nullable=False),
    sa.Column('role_label', sa.String(length=200), nullable=False),
    sa.Column('batch_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_sessions_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_sessions_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_session_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('pdf_filename', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['test_session_id'], ['test_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_test_session_id'), ['test_session_id'], unique=False)

    op.create_table('round_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_session_id', sa.Integer(), nullable=False),
    sa.Column('round_key', sa.String(length=10), nullable=False),
    sa.Column('round_label', sa.String(length=200), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('attempted', sa.Integer(), nullable=True),
    sa.Column('correct', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('pass_threshold', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_session_id'], ['test_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('round_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_round_results_test_session_id'), ['test_session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('round_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_round_results_test_session_id'))

    op.drop_table('round_results')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_test_session_id'))

    op.drop_table('reports')
    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_sessions_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_test_sessions_batch_id'))

    op.drop_table('test_sessions')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_email'))

    op.drop_table('candidates')
    # ### end Alembic commands ###
