ENTERPRISE_DEFAULT_BANK_VERSION = "enterprise_bank_v2"
ENTERPRISE_BALANCED_DIFFICULTY_MIX = {"easy": 5, "medium": 5, "hard": 5}
ENTERPRISE_ROLE_KEYS = {
    "python_entry",
    "js_entry",
    "python_qa",
    "python_qa_linux",
    "python_dev",
    "python_ai_ml",
    "java_entry",
    "java_qa",
    "java_aws",
    "bmc_engineer",
    "linux_kernel_dd",
    "systems_architect_cpp",
    "csharp_dev",
}

ENTERPRISE_ROLE_ROUND_BANKS = {
    ("python_entry", "L2"): ["python/python_entry_theory_debug.json"],
    ("js_entry", "L2"): ["java_script/js_entry_theory_debug.json"],
    ("python_qa", "L2"): ["python/python_senior_theory_debug.json"],
    ("python_qa", "L3"): ["qa/python_qa_enterprise_ui.json"],
    ("python_qa", "L3A"): ["qa/python_qa_enterprise_api.json"],
    ("python_qa_linux", "L1"): ["linux/linux_fundamentals_enterprise.json"],
    ("python_qa_linux", "L2"): ["python/python_senior_theory_debug.json"],
    ("python_qa_linux", "L3"): ["qa/python_qa_enterprise_ui.json", "qa/python_qa_enterprise_api.json"],
    ("python_dev", "L2"): ["python/python_senior_theory_debug.json"],
    ("python_dev", "L3"): ["dev/python_dev_engineering.json"],
    ("python_ai_ml", "L2"): ["python/python_senior_theory_debug.json"],
    ("python_ai_ml", "L3"): ["AI/ML/ai_ml_engineering.json"],
    ("java_entry", "L2"): ["java/java_entry_theory.json"],
    ("java_qa", "L2"): ["java/java_senior_theory_debug.json"],
    ("java_qa", "L3"): ["qa/java_qa_advanced.json"],
    ("java_aws", "L2"): ["java/java_senior_theory_debug.json"],
    ("java_aws", "L3"): ["cloud/java_aws_cloud.json"],
    ("bmc_engineer", "L2"): ["c/c_senior_theory_debug.json"],
    ("bmc_engineer", "L3"): ["bmc/bmc_firmware_engineering.json"],
    ("linux_kernel_dd", "L1"): ["c/c_senior_theory_debug.json"],
    ("linux_kernel_dd", "L2"): ["linux/linux_kernel_engineering.json"],
    ("linux_kernel_dd", "L3"): ["device_driver/device_driver_engineering.json"],
    ("systems_architect_cpp", "L2"): ["cpp/cpp_senior_theory_debug.json"],
    ("systems_architect_cpp", "L3"): ["system_design/cpp_system_design_architecture.json"],
    ("csharp_dev", "L2"): ["csharp/csharp_senior_theory_debug.json"],
    ("csharp_dev", "L3"): ["dev/csharp_dev_foundations.json"],
}

ENTRY_DIFFICULTY_COUNTS = {"easy": 40, "medium": 35, "hard": 25}
ENTRY_DEBUGGING_COUNTS = {"easy": 6, "medium": 8, "hard": 6}
SENIOR_DIFFICULTY_COUNTS = {"easy": 25, "medium": 35, "hard": 40}
SENIOR_DEBUGGING_COUNTS = {"easy": 6, "medium": 13, "hard": 16}
ADVANCED_DIFFICULTY_COUNTS = {"easy": 20, "medium": 35, "hard": 45}
ADVANCED_DEBUGGING_COUNTS = {"easy": 5, "medium": 15, "hard": 25}

ENTRY_POLICY_TEMPLATE = {
    "difficulty_counts": ENTRY_DIFFICULTY_COUNTS,
    "debugging_counts": ENTRY_DEBUGGING_COUNTS,
    "min_selected_debugging": 3,
    "selected_debugging_by_difficulty": {"easy": 1, "medium": 1, "hard": 1},
    "min_applied_ratio": 0.40,
    "max_output_ratio": 0.12,
    "max_output_prefix_ratio": 0.18,
}

SENIOR_POLICY_TEMPLATE = {
    "difficulty_counts": SENIOR_DIFFICULTY_COUNTS,
    "debugging_counts": SENIOR_DEBUGGING_COUNTS,
    "min_selected_debugging": 5,
    "min_applied_ratio": 0.55,
    "max_output_ratio": 0.10,
    "max_output_prefix_ratio": 0.08,
}

ADVANCED_POLICY_TEMPLATE = {
    "difficulty_counts": ADVANCED_DIFFICULTY_COUNTS,
    "debugging_counts": ADVANCED_DEBUGGING_COUNTS,
    "min_selected_debugging": 5,
    "min_applied_ratio": 0.60,
    "max_output_ratio": 0.08,
    "max_output_prefix_ratio": 0.05,
}

SHARED_POOL_POLICY_TEMPLATE = {
    "min_selected_debugging": 0,
    "min_applied_ratio": 0.02,
    "max_output_ratio": 0.18,
    "max_output_prefix_ratio": 0.22,
    "max_definition_ratio": 0.70,
}

ENTERPRISE_BANK_POLICIES = {
    "python/python_entry_theory_debug.json": {
        **ENTRY_POLICY_TEMPLATE,
        "role_key": "python_entry",
        "round_key": "L2",
        "bank_version": "enterprise_py_entry_easy_only_v3",
        "difficulty_counts": {"easy": 50, "medium": 0, "hard": 0},
        "debugging_counts": {"easy": 11, "medium": 0, "hard": 0},
        "selection_difficulty_mix": {"easy": 15},
        "selected_debugging_by_difficulty": {"easy": 3},
        "required_topics": {
            "Python Language Fundamentals",
            "Data Structures and Collections",
            "Functions and OOP",
            "Exceptions and Debugging",
            "Modules and Tooling",
            "Standard Library Usage",
            "Testing Basics",
        },
    },
    "java_script/js_entry_theory_debug.json": {
        **ENTRY_POLICY_TEMPLATE,
        "role_key": "js_entry",
        "round_key": "L2",
        "bank_version": "enterprise_js_entry_v1",
        "required_topics": {
            "JavaScript Language Fundamentals",
            "Data Types and Structures",
            "Functions and Scope",
            "Async and Promises",
            "Browser and DOM Basics",
            "Node.js Fundamentals",
            "Debugging Fundamentals",
        },
    },
    "python/python_senior_theory_debug.json": {
        **SENIOR_POLICY_TEMPLATE,
        "role_key": "python_shared_senior",
        "round_key": "L2",
        "bank_version": "enterprise_python_shared_hard_only_v4",
        "difficulty_counts": {"easy": 0, "medium": 0, "hard": 35},
        "debugging_counts": {"easy": 0, "medium": 0, "hard": 35},
        "selection_difficulty_mix": {"hard": 15},
        "required_topics": {
            "Data Structures and Performance",
            "Python Language and Runtime",
            "Functions and Call Semantics",
            "OOP and Design",
            "Iterators and Comprehensions",
            "Exceptions and Debugging",
            "Practical Debugging",
        },
    },
    "qa/python_qa_enterprise_ui.json": {
        "role_key": "python_qa_shared",
        "round_key": "L3",
        "bank_version": "enterprise_python_qa_ui_v1",
        "difficulty_counts": {"easy": 39, "medium": 37, "hard": 37},
        "debugging_counts": {"easy": 1, "medium": 4, "hard": 2},
        "min_selected_debugging": 0,
        "required_topics": set(),
        "min_applied_ratio": 0.0,
        "max_output_ratio": 1.0,
        "max_output_prefix_ratio": 1.0,
        "max_definition_ratio": 1.0,
        "strict_validation": False,
    },
    "qa/python_qa_enterprise_api.json": {
        "role_key": "python_qa_shared",
        "round_key": "L3",
        "bank_version": "enterprise_python_qa_api_v1",
        "difficulty_counts": {"easy": 35, "medium": 40, "hard": 30},
        "debugging_counts": {"easy": 3, "medium": 2, "hard": 1},
        "min_selected_debugging": 0,
        "required_topics": set(),
        "min_applied_ratio": 0.0,
        "max_output_ratio": 1.0,
        "max_output_prefix_ratio": 1.0,
        "max_definition_ratio": 1.0,
        "strict_validation": False,
    },
    "qa/python_qa_linux_advanced.json": {
        **ADVANCED_POLICY_TEMPLATE,
        "role_key": "python_qa_linux",
        "round_key": "L3",
        "bank_version": "enterprise_python_qa_linux_v1",
        "required_topics": {
            "Linux QA Operations",
            "Python Test Automation",
            "API and Integration Testing",
            "Test Framework Architecture",
            "CI and Reliability",
            "Performance and Troubleshooting",
            "Debugging and Root Cause",
        },
    },
    "dev/python_dev_engineering.json": {
        **ADVANCED_POLICY_TEMPLATE,
        "role_key": "python_dev",
        "round_key": "L3",
        "bank_version": "enterprise_python_dev_v1",
        "required_topics": {
            "Backend Architecture",
            "API Design and Contracts",
            "Data Access and ORM",
            "Performance and Scalability",
            "Concurrency and Reliability",
            "Testing and Observability",
            "Debugging and Incident Response",
        },
    },
    "AI/ML/ai_ml_engineering.json": {
        "role_key": "python_ai_ml",
        "round_key": "L3",
        "bank_version": "enterprise_ai_ml_v1",
        "difficulty_counts": {"easy": 25, "medium": 35, "hard": 40},
        "debugging_counts": {"easy": 5, "medium": 12, "hard": 18},
        "style_counts": {"concept": 20, "scenario": 25, "debugging": 35, "architecture": 10, "operations": 10},
        "min_selected_debugging": 5,
        "required_topics": {
            "Data Splitting, Leakage, and Experiment Design",
            "Feature Engineering and Representation Learning",
            "Classical ML Algorithms and Optimization",
            "Model Evaluation, Calibration, and Fairness",
            "Deep Learning Training and Troubleshooting",
            "LLMs, Embeddings, and RAG Systems",
            "NLP and Text Systems",
            "Computer Vision and Multimodal Systems",
            "Ranking, Retrieval, and Recommendation",
            "MLOps, Deployment, and Monitoring",
        },
        "expected_topic_counts": {
            "Data Splitting, Leakage, and Experiment Design": 10,
            "Feature Engineering and Representation Learning": 10,
            "Classical ML Algorithms and Optimization": 15,
            "Model Evaluation, Calibration, and Fairness": 15,
            "Deep Learning Training and Troubleshooting": 15,
            "LLMs, Embeddings, and RAG Systems": 10,
            "NLP and Text Systems": 7,
            "Computer Vision and Multimodal Systems": 6,
            "Ranking, Retrieval, and Recommendation": 5,
            "MLOps, Deployment, and Monitoring": 7,
        },
        "min_applied_ratio": 0.65,
        "max_output_ratio": 0.05,
        "max_output_prefix_ratio": 0.05,
        "max_definition_ratio": 0.10,
    },
    "java/java_entry_theory.json": {
        **ENTRY_POLICY_TEMPLATE,
        "role_key": "java_entry",
        "round_key": "L2",
        "bank_version": "enterprise_java_v2",
        "required_topics": {
            "Java Language Fundamentals",
            "Strings and Immutability",
            "Exceptions",
            "Collections Basics",
            "Lambdas and Streams",
            "Methods and References",
            "Debugging Fundamentals",
        },
    },
    "java/java_senior_theory_debug.json": {
        **SENIOR_POLICY_TEMPLATE,
        "role_key": "java_shared_senior",
        "round_key": "L2",
        "bank_version": "enterprise_java_v2",
        "required_topics": {
            "Java Language and Type System",
            "Strings and Immutability",
            "Collections and Contracts",
            "Generics and Type Safety",
            "Exceptions and Resource Handling",
            "Streams Lambdas and Method References",
            "Concurrency and Executors",
            "JVM Memory and GC",
            "Practical Debugging",
        },
        "allowed_topics": {
            "Java Language and Type System",
            "Strings and Immutability",
            "Collections and Contracts",
            "Generics and Type Safety",
            "Exceptions and Resource Handling",
            "Streams Lambdas and Method References",
            "Concurrency and Executors",
            "JVM Memory and GC",
            "Practical Debugging",
        },
        "forbidden_patterns": (
            r"\bqa\b",
            r"selenium",
            r"webdriver",
            r"testng",
            r"junit",
            r"rest assured",
            r"\bapi tests?\b",
            r"\bapi testing\b",
            r"\bhttp client\b",
            r"\bhttp request\b",
            r"\baws\b",
            r"lambda function",
            r"cloudwatch",
            r"\biam\b",
            r"\bsts\b",
            r"eventbridge",
            r"\bsqs\b",
            r"\bsns\b",
            r"spring boot",
            r"actuator",
        ),
        "forbidden_prefixes": (
            "during a qa test",
            "a qa engineer",
            "your api",
            "lambda",
            "aws",
            "cloudwatch",
            "selenium",
        ),
    },
    "qa/java_qa_advanced.json": {
        **ADVANCED_POLICY_TEMPLATE,
        "role_key": "java_qa",
        "round_key": "L3",
        "bank_version": "enterprise_java_v2",
        "debugging_counts": {"easy": 6, "medium": 16, "hard": 23},
        "required_topics": {
            "JUnit Jupiter",
            "TestNG Execution",
            "Selenium WebDriver",
            "FluentWait and Synchronization",
            "REST Assured",
            "Framework Architecture",
            "CI Failure Triage",
        },
    },
    "cloud/java_aws_cloud.json": {
        **ADVANCED_POLICY_TEMPLATE,
        "role_key": "java_aws",
        "round_key": "L3",
        "bank_version": "enterprise_java_v2",
        "required_topics": {
            "Spring Boot Production Readiness",
            "Actuator and Management Security",
            "AWS SDK v2 Credentials",
            "IAM and STS",
            "Lambda and SnapStart",
            "Observability",
            "Cloud Runtime Debugging",
        },
    },
    "c/c_senior_theory_debug.json": {
        **SENIOR_POLICY_TEMPLATE,
        "role_key": "c_shared_senior",
        "round_key": "L2",
        "bank_version": "enterprise_c_senior_v1",
        "required_topics": {
            "C Language Fundamentals",
            "Pointers and Memory Safety",
            "Data Structures and Algorithms in C",
            "Build Toolchain and Linking",
            "Systems Programming Concepts",
            "Concurrency and Synchronization in C",
            "Practical Debugging",
        },
    },
    "bmc/bmc_firmware_engineering.json": {
        **ADVANCED_POLICY_TEMPLATE,
        "role_key": "bmc_engineer",
        "round_key": "L3",
        "bank_version": "enterprise_bmc_v1",
        "required_topics": {
            "Embedded C and Firmware Basics",
            "BMC Architecture and Interfaces",
            "Boot and Initialization",
            "Hardware Communication and Protocols",
            "Reliability and Fault Handling",
            "Performance and Resource Constraints",
            "Firmware Debugging",
        },
    },
    "linux/linux_fundamentals_enterprise.json": {
        **SENIOR_POLICY_TEMPLATE,
        "role_key": "linux_shared",
        "round_key": "L1",
        "bank_version": "enterprise_linux_fundamentals_v1",
        "required_topics": {
            "Linux Fundamentals and CLI",
            "Filesystem and Permissions",
            "Process and Service Management",
            "Networking and Security Basics",
            "Shell Scripting and Automation",
            "Monitoring and Troubleshooting",
            "Linux Debugging",
        },
    },
    "linux/linux_kernel_engineering.json": {
        **ADVANCED_POLICY_TEMPLATE,
        "role_key": "linux_kernel_dd",
        "round_key": "L2",
        "bank_version": "enterprise_linux_kernel_v1",
        "required_topics": {
            "Kernel Architecture and Internals",
            "Scheduling and Memory Management",
            "Kernel Concurrency and Locking",
            "Kernel APIs and Subsystems",
            "Performance and Observability",
            "Kernel Build and Deployment",
            "Kernel Debugging",
        },
    },
    "device_driver/device_driver_engineering.json": {
        **ADVANCED_POLICY_TEMPLATE,
        "role_key": "linux_kernel_dd",
        "round_key": "L3",
        "bank_version": "enterprise_device_driver_v1",
        "required_topics": {
            "Driver Model and Lifecycle",
            "Memory and DMA Handling",
            "Interrupts and Concurrency",
            "I/O Paths and Subsystems",
            "Driver Reliability and Error Handling",
            "Driver Performance and Diagnostics",
            "Driver Debugging",
        },
    },
    "cpp/cpp_senior_theory_debug.json": {
        **SENIOR_POLICY_TEMPLATE,
        "role_key": "cpp_shared_senior",
        "round_key": "L2",
        "bank_version": "enterprise_cpp_senior_v1",
        "required_topics": {
            "C++ Language and Type System",
            "Memory Management and RAII",
            "STL and Performance",
            "Concurrency and Synchronization",
            "OOP and Design Patterns",
            "Build Tooling and Modern C++",
            "Practical Debugging",
        },
    },
    "system_design/cpp_system_design_architecture.json": {
        **ADVANCED_POLICY_TEMPLATE,
        "role_key": "systems_architect_cpp",
        "round_key": "L3",
        "bank_version": "enterprise_cpp_architecture_v1",
        "required_topics": {
            "Distributed System Design",
            "Scalability and Performance",
            "Reliability and Fault Tolerance",
            "Data and Storage Architecture",
            "API and Integration Architecture",
            "Observability and Operations",
            "Architectural Debugging",
        },
    },
    "csharp/csharp_senior_theory_debug.json": {
        **SENIOR_POLICY_TEMPLATE,
        "role_key": "csharp_dev",
        "round_key": "L2",
        "bank_version": "enterprise_csharp_senior_v1",
        "required_topics": {
            "C# Language Fundamentals",
            "Collections and LINQ",
            "Async and Concurrency",
            ".NET Runtime and Memory",
            "API and Backend Patterns",
            "Testing and Reliability",
            "Practical Debugging",
        },
    },
    "dev/csharp_dev_foundations.json": {
        **ADVANCED_POLICY_TEMPLATE,
        "role_key": "csharp_dev",
        "round_key": "L3",
        "bank_version": "enterprise_csharp_dev_v1",
        "required_topics": {
            "C# Backend Foundations",
            "API Design and Contracts",
            "Data Access and Persistence",
            "Performance and Scalability",
            "CI CD and Observability",
            "Security and Reliability",
            "Debugging and Incident Response",
        },
    },
    "aptitude.json": {
        **SHARED_POOL_POLICY_TEMPLATE,
        "role_key": "shared_aptitude",
        "round_key": "L1",
        "bank_version": "enterprise_shared_v1",
        "difficulty_counts": {"easy": 124, "medium": 108, "hard": 77},
        "debugging_counts": {"easy": 0, "medium": 0, "hard": 0},
        "required_topics": set(),
    },
    "soft_skills.json": {
        **SHARED_POOL_POLICY_TEMPLATE,
        "role_key": "shared_soft_skills",
        "round_key": "L5",
        "bank_version": "enterprise_shared_v1",
        "difficulty_counts": {"easy": 30, "medium": 26, "hard": 19},
        "debugging_counts": {"easy": 0, "medium": 0, "hard": 0},
        "required_topics": set(),
    },
    "soft_skills_leadership.json": {
        **SHARED_POOL_POLICY_TEMPLATE,
        "role_key": "shared_soft_skills_leadership",
        "round_key": "L5",
        "bank_version": "enterprise_shared_v1",
        "difficulty_counts": {"easy": 20, "medium": 18, "hard": 12},
        "debugging_counts": {"easy": 0, "medium": 0, "hard": 0},
        "required_topics": set(),
    },
    "domains/networking.json": {
        **SHARED_POOL_POLICY_TEMPLATE,
        "role_key": "shared_domain_networking",
        "round_key": "L6",
        "bank_version": "enterprise_shared_v1",
        "difficulty_counts": {"easy": 48, "medium": 42, "hard": 30},
        "debugging_counts": {"easy": 0, "medium": 0, "hard": 0},
        "required_topics": set(),
    },
    "domains/storage.json": {
        **SHARED_POOL_POLICY_TEMPLATE,
        "role_key": "shared_domain_storage",
        "round_key": "L6",
        "bank_version": "enterprise_shared_v1",
        "difficulty_counts": {"easy": 24, "medium": 21, "hard": 16},
        "debugging_counts": {"easy": 0, "medium": 0, "hard": 0},
        "required_topics": set(),
    },
    "domains/virtualisation.json": {
        **SHARED_POOL_POLICY_TEMPLATE,
        "role_key": "shared_domain_virtualization",
        "round_key": "L6",
        "bank_version": "enterprise_shared_v1",
        "difficulty_counts": {"easy": 48, "medium": 42, "hard": 30},
        "debugging_counts": {"easy": 0, "medium": 0, "hard": 0},
        "required_topics": set(),
    },
}


def get_enterprise_bank_files(role_key, round_key):
    return ENTERPRISE_ROLE_ROUND_BANKS.get((role_key, round_key), [])


def get_enterprise_bank_policy(source_name=None, role_key=None, round_key=None):
    if source_name:
        return ENTERPRISE_BANK_POLICIES.get(source_name)
    if role_key and round_key:
        files = get_enterprise_bank_files(role_key, round_key)
        if len(files) == 1:
            return ENTERPRISE_BANK_POLICIES.get(files[0])
    return None


def is_enterprise_role(role_key):
    return role_key in ENTERPRISE_ROLE_KEYS
