ENTERPRISE_DEFAULT_BANK_VERSION = 'enterprise_bank_v1'
ENTERPRISE_BALANCED_DIFFICULTY_MIX = {'easy': 5, 'medium': 5, 'hard': 5}
ENTERPRISE_ROLE_KEYS = {'java_entry', 'java_qa', 'java_aws', 'python_ai_ml'}

ENTERPRISE_ROLE_ROUND_BANKS = {
    ('java_entry', 'L2'): ['java/java_entry_theory.json'],
    ('java_entry', 'L3'): ['java/java_entry_fundamentals.json'],
    ('java_qa', 'L2'): ['java/java_senior_theory_debug.json'],
    ('java_qa', 'L3'): ['qa/java_qa_advanced.json'],
    ('java_aws', 'L2'): ['java/java_senior_theory_debug.json'],
    ('java_aws', 'L3'): ['cloud/java_aws_cloud.json'],
    ('python_ai_ml', 'L3'): ['AI/ML/ai_ml_engineering.json'],
}

ENTERPRISE_BANK_POLICIES = {
    'java/java_entry_theory.json': {
        'role_key': 'java_entry',
        'round_key': 'L2',
        'bank_version': 'enterprise_java_v2',
        'difficulty_counts': {'easy': 40, 'medium': 35, 'hard': 25},
        'debugging_counts': {'easy': 6, 'medium': 8, 'hard': 6},
        'min_selected_debugging': 3,
        'selected_debugging_by_difficulty': {'easy': 1, 'medium': 1, 'hard': 1},
        'required_topics': {
            'Java Language Fundamentals',
            'Strings and Immutability',
            'Exceptions',
            'Collections Basics',
            'Lambdas and Streams',
            'Methods and References',
            'Debugging Fundamentals',
        },
        'min_applied_ratio': 0.40,
        'max_output_ratio': 0.10,
        'max_output_prefix_ratio': 0.20,
    },
    'java/java_senior_theory_debug.json': {
        'role_key': 'java_shared_senior',
        'round_key': 'L2',
        'bank_version': 'enterprise_java_v2',
        'difficulty_counts': {'easy': 25, 'medium': 35, 'hard': 40},
        'debugging_counts': {'easy': 6, 'medium': 13, 'hard': 16},
        'min_selected_debugging': 5,
        'required_topics': {
            'Java Language and Type System',
            'Strings and Immutability',
            'Collections and Contracts',
            'Generics and Type Safety',
            'Exceptions and Resource Handling',
            'Streams Lambdas and Method References',
            'Concurrency and Executors',
            'JVM Memory and GC',
            'Practical Debugging',
        },
        'allowed_topics': {
            'Java Language and Type System',
            'Strings and Immutability',
            'Collections and Contracts',
            'Generics and Type Safety',
            'Exceptions and Resource Handling',
            'Streams Lambdas and Method References',
            'Concurrency and Executors',
            'JVM Memory and GC',
            'Practical Debugging',
        },
        'forbidden_patterns': (
            r'\bqa\b',
            r'selenium',
            r'webdriver',
            r'testng',
            r'junit',
            r'rest assured',
            r'\bapi tests?\b',
            r'\bapi testing\b',
            r'\bhttp client\b',
            r'\bhttp request\b',
            r'\baws\b',
            r'lambda function',
            r'cloudwatch',
            r'\biam\b',
            r'\bsts\b',
            r'eventbridge',
            r'\bsqs\b',
            r'\bsns\b',
            r'spring boot',
            r'actuator',
        ),
        'forbidden_prefixes': (
            'during a qa test',
            'a qa engineer',
            'your api',
            'lambda',
            'aws',
            'cloudwatch',
            'selenium',
        ),
        'min_applied_ratio': 0.60,
        'max_output_ratio': 0.10,
        'max_output_prefix_ratio': 0.05,
    },
    'java/java_entry_fundamentals.json': {
        'role_key': 'java_entry',
        'round_key': 'L3',
        'bank_version': 'enterprise_java_v2',
        'difficulty_counts': {'easy': 40, 'medium': 35, 'hard': 25},
        'debugging_counts': {'easy': 8, 'medium': 10, 'hard': 7},
        'min_selected_debugging': 3,
        'required_topics': {
            'Collections Contracts',
            'Generics and Type Safety',
            'NIO and Files',
            'Concurrency Basics',
            'Executor Patterns',
            'Test Utility Design',
            'Debugging Fundamentals',
        },
        'min_applied_ratio': 0.45,
        'max_output_ratio': 0.10,
        'max_output_prefix_ratio': 0.18,
    },
    'java/java_qa_core.json': {
        'role_key': 'java_qa',
        'round_key': 'L2',
        'bank_version': 'enterprise_java_v2',
        'difficulty_counts': {'easy': 30, 'medium': 35, 'hard': 35},
        'debugging_counts': {'easy': 8, 'medium': 14, 'hard': 13},
        'min_selected_debugging': 5,
        'required_topics': {
            'Collections Contracts',
            'Exceptions and Retries',
            'Streams in Test Data',
            'Parallel Test Execution',
            'Automation Design',
            'JSON and HTTP Clients',
            'Debugging Automation Utilities',
        },
        'min_applied_ratio': 0.60,
        'max_output_ratio': 0.10,
        'max_output_prefix_ratio': 0.08,
    },
    'qa/java_qa_advanced.json': {
        'role_key': 'java_qa',
        'round_key': 'L3',
        'bank_version': 'enterprise_java_v2',
        'difficulty_counts': {'easy': 20, 'medium': 35, 'hard': 45},
        'debugging_counts': {'easy': 6, 'medium': 16, 'hard': 23},
        'min_selected_debugging': 5,
        'required_topics': {
            'JUnit Jupiter',
            'TestNG Execution',
            'Selenium WebDriver',
            'FluentWait and Synchronization',
            'REST Assured',
            'Framework Architecture',
            'CI Failure Triage',
        },
        'min_applied_ratio': 0.60,
        'max_output_ratio': 0.10,
        'max_output_prefix_ratio': 0.05,
    },
    'java/java_aws_advanced.json': {
        'role_key': 'java_aws',
        'round_key': 'L2',
        'bank_version': 'enterprise_java_v2',
        'difficulty_counts': {'easy': 25, 'medium': 35, 'hard': 40},
        'debugging_counts': {'easy': 6, 'medium': 13, 'hard': 16},
        'min_selected_debugging': 5,
        'required_topics': {
            'Collections Contracts',
            'Concurrency and Executors',
            'Virtual Threads',
            'JVM Memory and GC',
            'Spring Boot Architecture',
            'Resilience Patterns',
            'Backend Debugging',
        },
        'min_applied_ratio': 0.60,
        'max_output_ratio': 0.10,
        'max_output_prefix_ratio': 0.05,
    },
    'cloud/java_aws_cloud.json': {
        'role_key': 'java_aws',
        'round_key': 'L3',
        'bank_version': 'enterprise_java_v2',
        'difficulty_counts': {'easy': 20, 'medium': 35, 'hard': 45},
        'debugging_counts': {'easy': 5, 'medium': 15, 'hard': 25},
        'min_selected_debugging': 5,
        'required_topics': {
            'Spring Boot Production Readiness',
            'Actuator and Management Security',
            'AWS SDK v2 Credentials',
            'IAM and STS',
            'Lambda and SnapStart',
            'Observability',
            'Cloud Runtime Debugging',
        },
        'min_applied_ratio': 0.60,
        'max_output_ratio': 0.10,
        'max_output_prefix_ratio': 0.05,
    },
    'AI/ML/ai_ml_engineering.json': {
        'role_key': 'python_ai_ml',
        'round_key': 'L3',
        'bank_version': 'enterprise_ai_ml_v1',
        'difficulty_counts': {'easy': 25, 'medium': 35, 'hard': 40},
        'debugging_counts': {'easy': 5, 'medium': 12, 'hard': 18},
        'style_counts': {'concept': 20, 'scenario': 25, 'debugging': 35, 'architecture': 10, 'operations': 10},
        'min_selected_debugging': 5,
        'required_topics': {
            'Data Splitting, Leakage, and Experiment Design',
            'Feature Engineering and Representation Learning',
            'Classical ML Algorithms and Optimization',
            'Model Evaluation, Calibration, and Fairness',
            'Deep Learning Training and Troubleshooting',
            'LLMs, Embeddings, and RAG Systems',
            'NLP and Text Systems',
            'Computer Vision and Multimodal Systems',
            'Ranking, Retrieval, and Recommendation',
            'MLOps, Deployment, and Monitoring',
        },
        'expected_topic_counts': {
            'Data Splitting, Leakage, and Experiment Design': 10,
            'Feature Engineering and Representation Learning': 10,
            'Classical ML Algorithms and Optimization': 15,
            'Model Evaluation, Calibration, and Fairness': 15,
            'Deep Learning Training and Troubleshooting': 15,
            'LLMs, Embeddings, and RAG Systems': 10,
            'NLP and Text Systems': 7,
            'Computer Vision and Multimodal Systems': 6,
            'Ranking, Retrieval, and Recommendation': 5,
            'MLOps, Deployment, and Monitoring': 7,
        },
        'min_applied_ratio': 0.65,
        'max_output_ratio': 0.05,
        'max_output_prefix_ratio': 0.05,
        'max_definition_ratio': 0.10,
    },
}


def get_enterprise_bank_files(role_key, round_key):
    return ENTERPRISE_ROLE_ROUND_BANKS.get((role_key, round_key), [])


def get_enterprise_bank_policy(source_name=None, role_key=None, round_key=None):
    if source_name:
        return ENTERPRISE_BANK_POLICIES.get(source_name)
    if role_key and round_key:
        files = get_enterprise_bank_files(role_key, round_key)
        if len(files) == 1:
            return ENTERPRISE_BANK_POLICIES.get(files[0])
    return None


def is_enterprise_role(role_key):
    return role_key in ENTERPRISE_ROLE_KEYS
